const menuToggle=document.querySelector('.menu-toggle');const navLinks=document.querySelector('.nav-links');menuToggle?.addEventListener('click',()=>{const open=menuToggle.getAttribute('aria-expanded')==='true';menuToggle.setAttribute('aria-expanded',String(!open));navLinks.classList.toggle('open');document.body.style.overflow=open?'':'hidden'});document.querySelectorAll('.nav-links a').forEach(link=>link.addEventListener('click',()=>{navLinks.classList.remove('open');menuToggle?.setAttribute('aria-expanded','false');document.body.style.overflow=''}));

const revealObserver=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}})},{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));

const filterButtons=document.querySelectorAll('.filter-btn');const products=document.querySelectorAll('.product-card');filterButtons.forEach(button=>button.addEventListener('click',()=>{filterButtons.forEach(btn=>btn.classList.remove('active'));button.classList.add('active');const filter=button.dataset.filter;products.forEach(card=>{const categories=card.dataset.category.split(' ');card.classList.toggle('hidden',filter!=='all'&&!categories.includes(filter))})}));

document.querySelectorAll('.quick-view').forEach(button=>button.addEventListener('click',()=>{const product=button.dataset.product;const message=`Hello Anamika Sarees, I would like to enquire about ${product}. Please share more details.`;window.open(`https://wa.me/919111985445?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')}));

const testimonials=[...document.querySelectorAll('.testimonial')];let testimonialIndex=0;function showTestimonial(index){testimonials.forEach(item=>item.classList.remove('active'));testimonialIndex=(index+testimonials.length)%testimonials.length;testimonials[testimonialIndex].classList.add('active')}document.querySelector('.next')?.addEventListener('click',()=>showTestimonial(testimonialIndex+1));document.querySelector('.prev')?.addEventListener('click',()=>showTestimonial(testimonialIndex-1));

const appointmentForm=document.querySelector('#appointment-form');const formStatus=document.querySelector('#form-status');appointmentForm?.addEventListener('submit',event=>{event.preventDefault();const data=new FormData(appointmentForm);const name=data.get('name')?.toString().trim();const phone=data.get('phone')?.toString().replace(/\D/g,'');const occasion=data.get('occasion');const collection=data.get('collection');const details=data.get('message')?.toString().trim();if(!name||!phone||phone.length<10||!occasion||!collection){formStatus.textContent='Please complete your name, valid phone number, occasion and collection.';return}formStatus.textContent='Opening WhatsApp…';const message=[`Hello Anamika Sarees, I would like to book a personal shopping appointment.`,`Name: ${name}`,`Phone: ${phone}`,`Occasion: ${occasion}`,`Interested in: ${collection}`,details?`Preferences: ${details}`:''].filter(Boolean).join('\n');window.open(`https://wa.me/919111985445?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer')});

document.querySelector('#year').textContent=new Date().getFullYear();
